[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2068a65d4c8fd6b35198f7566efa14d4566344ad"
os = "macos"

    [[MLIR.download]]
    sha256 = "36bc3b5ef226131fc2b7af9ac9efd13a53dcd9ade23cc83cee85ec713caaceaf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1d39e6a4064238dbf7751bde5cf04684e1cc4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c7f58e7dcbe1da017e05c2b87410b338571171754446f1c5aad8d1570ef4ff31"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff66d997feb96b10a4b08428aff74d01e9b4f69"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "ed3fd64cb4e161a052d12d22609ddbce401bed5b65aa8e709439a6446218b739"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223490c58a9b298b7ce5f9354e28b665aec2e719"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "3204ecaa8718a7036d06a333730fce6eb6309e5938684e5091657b717fbe1397"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599b0c45546d648cbd2102a63899a9f624947d3b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "fa831fe007aff3fbf08789d59e050b66e8ee2902008a402d76673ee4179532a7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86239578761bb938f7f65901bc541d2243df9d61"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b9cc466751741f458b8b30f1f76fff1083896f14d54f62c8c56f60cdee3c6e68"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e94953616fb62439ca136f23219e99973cb3c1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f7d32f62b5216863afcf075872a47e369080643a50a2ff0d1120c181ac5741d3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6406c3cde90ac0ac0e50d83e3e3df605089353"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "b074c4016d2e35352c7f44ac766cfa65f5635940be639471913e699778c049d7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cf0fa9c543ae2d07bf93dce160c04a6ebd2c5b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "f5add3aafe1c56f4c58161b548eccd7702603ad60af1a960b01ac0c6070a91d1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b44c711c2c85036ad7ef75c820b1872822a99e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b595392ac30312f845d07cc880afd4b5b63a3ab1c1d0fcf6b97befd351017876"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f270723ccea3487583cf90599db57e55fcdde0bf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2a8a1344849d7893d02440e5fe8c6e5dd42f6fe03eaa8ed3513b0e59b18b8995"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2f42158f55d9508b6ef627c691707d51c795744"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "8ec59e157d21c67b87cae569eb2d96313d389d4e5f65f4d6a753dd4877898895"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84084fda385a252379bd63f1a9e2fcddb031d8f"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "35f34ed7a99ee19a861b0c6107e0ae550f5f2850f6ecb5a6050c51c7cd4b58df"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97c1caa65c4a0a6ff89f5de9f1835205bd730ce"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d96a45a0c27be088f632216c37694756bc32b3cf34fe2323a8305cbd831090c8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e77ad3e0cb9566862ed5bcd10d002026c407e9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "426d706ebe9e7f58b57c971ce5ac4a667e8e915091cd6a1671e250c341c066c0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8cf1cb1ec0b1efa1b92004dffe874b53052f0ea"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "03494da13ab5c58a335b11e06acfba8efe8466269256ccb333f7de6269798c4d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2364d5ecb7f828d0e278e148d34a71b56d93e87"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "3827b15c739581be47c48bc9d7338fa8f931864ff1d354c41932fc230be48416"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da1fd27bd21a26e81d8d3952e0ef72a1a895df1"
os = "windows"

    [[MLIR.download]]
    sha256 = "dbac92c11819b453c4470f4f5b5591de7e9c3769e7f30afb6450f67c7b870fed"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f751dcb9adf13873787b56a1fba5db3ed2d1293"
os = "windows"

    [[MLIR.download]]
    sha256 = "f5607d59b95ea693da275560f24c7541b07fe6a191a1c3a2d9393107a019d915"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7418e58cfc6c6c2fa57597999afa8a7a3c4e79b3"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "1e94e8370a9e7afceeeb807ee6e6e22d86b41be3fc18f3fc6ff79d2dd81544a0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78bfa1d82861a59c149f63f6dd95a892c597a059"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "89a1fd74cdb45b5c17c0e897bd5731c98bcd97e1d830b4531c3fb61015131bd7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "42beab69c720ba2d8503707e6f6dfb822a7ff92e"
os = "macos"

    [[MLIR.download]]
    sha256 = "170ea5aca5e55fb3cf11e02227604dc4a83538fc929389008e02602936f076bb"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "529866c736e4d3dca2fd9af5587c84c9ba4f2b1a"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c82d62cc269306507ff3d1d9fcb289edb5ea6efb2267fb5685ecdb492cc1de8f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac65f46af335324d8c3e7f46b6274557224d81c"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b284543e4c05dee9e78c51a57febebb0211ff2cba2650ef601abf84fb740412d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21701d1b552b8e4749c9d784a7260996520d04db"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9c740fd839706d272a95b415eef062e519283f820694e94a5c1ddb5fee563289"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6c9ddf26a9ffab0e30230d85db1af4f754635d1"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "7aee842efd1df86fb33fc5995faa3c5856f46cace14523b18a05b157c280a793"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad39b29c4bac16e361694ac3d6db1de7d6fcd5c3"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "84bcd57059483bafd6ac9812f6c4cb77c0bb5864c555f0e3579d21338f4b8ee3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "535c46a728057caf4786281939f6035246231175"
os = "windows"

    [[MLIR.download]]
    sha256 = "4d4c2ef0f11689e382efa4e17cf800a6ee8140ef180bd9cf1b14fc5f6731e9f5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8eb1bf96ce6049d4786d347dbedccbdfebd561e"
os = "windows"

    [[MLIR.download]]
    sha256 = "e54bf7ecec9afd5822ddd357bbe21cdfb6ba149ea46bb6be2ccbae1b1b32c721"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
