[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "b1f7cd32839f6802f43e6b9e59e03336480c1b97"
os = "macos"

    [[MLIR.download]]
    sha256 = "6041cee768763eb7be6a0d63dc21b2378b73fae44edecdc84ad470a500f48228"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd19aae94f16b1dacc8e98e7c609560f7f0a8f5f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "78420d5645f537fc8bad73d207e18af5c1f9e3a61aaf0ec6d5c258fdf2b8e40f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eabeca2aa61f5df1d24b2480a02d6f8c2aba8479"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "014f2da1445d5d625094e59a6d9124ab5967daacbd83e26ce50eb7f25cb44d97"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1bac5f9570f9aa6d95b01b3efd68a1d2b04e49e"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "cca4d0ed2d53eeb7bbb3e36386da01de835ac2b449c56f0503a8e035a8a47e1a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71cd7b83d9e62fbaaff67765e996e85a35fcc557"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5c46b47917112947f4fd669a64d7c307f03934f9f52e98626cc1ec4b10566f9b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb2976368fbab712a2ab87d5e55231e0a6fd388"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3d5b08587eca53862baee4028825887a84b29a14cd26ab93410ca98ea668c6a9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2884b09ef4166257e8d18482c0221ec5850376f2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2a6447191ba7a63b55b10e832a50b478df4ce16f605a2dd16f30ba8f7bf10f35"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77bfddfebf3deae5f77cdeb6e7c737f34b72e12"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "7878090e1485b60e528aa7898149d5dfdaf0370c08eabd4b0145a55873ef2d66"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7728bf85a1544c230242a2ac026df0a17ea58a38"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "c7c97d7cb0f173b1f9cdbffd2b2b4c440e68e6e9fc6a5c4ac866ced5daa38721"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92468b949ca7f783cb620bd98e3d2e408a0c8ee"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "6fb7a9b61c923aa3cb2df79bc606046a9b6bae6d6255d1c3d159b418e4f03d1f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82fe8558327652a7d3028a4e8920b9f724a12221"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "4721757c857fbe498368f6eb61bcdb5900a0abde9af061586b0d838be00946c2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "567e8faa596a5d1d11726f8813a8666fb67a6f60"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "63c4db4dd0b9134bae5e69a53cdcb0234996b086da15b3cfc228090df7249394"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973db291e58c5eaebaeb42bc0a6fed066fb20640"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "75e3818a86bd7092d2e3af1632a62a3af9b5d35e5be322d02b71d796fcf5991c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94cfb83f1d57ff49ddd6ff039b147dd73edddca1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "5e024a86c9d9beecfb7c6af05852e45ce07bb2d5bbefdb901b62002e6be5a80c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6868870505051db5755c06945f0405c9996857cf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d4e8125a44d9a803e3cca2feeb8f66fa02434ec7afb9b2e27eb6b6a5ec9e1c27"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "398a7a3d42e2ee42f91a8fcbf3ab0158970e8812"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9f88d0f7d7f4b0146154cd3e7529d22464a19328e0cb54dc6c29b2a6c468bccf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfdcbeca5553896383e5706434233e1de96db0a0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "34ed80fbea03451133aa1c572e3ff0e920c79badbd2a752213347b7a52f731c8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c8c07e156c0c8fe688f7c46f70ba7d2b060cb853"
os = "windows"

    [[MLIR.download]]
    sha256 = "e2391741acddc7fd4ed01a4293dcc13956ac81b1b5930d5b66c3c501f1c70eaa"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe4eabbc5ebeed771af01650558873f555386f64"
os = "windows"

    [[MLIR.download]]
    sha256 = "3a4dc3127816fd3270efffd975617bd7525e8878d9f3d5c5313ae61dedc491d3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1263166316d30cf8a16825a7e2d01693aa4e4cc9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "314ddd6168436123cf2a3451011519821d61c35f6d4d1612eabbf4b983ef6ab6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e17815b54cb50ec2af1bad7f6c948350d61776f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2c9fd810543079f787ee9ff1c0bf38072dedabb57cbcc8bb18243c4c33c6a455"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "417369d36810977ca00a5eeaa5c9e2ebf746b91f"
os = "macos"

    [[MLIR.download]]
    sha256 = "090f18016288683692c1815689917ddb82e35824665ce308e679886af492123c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac3e6fb4ff2f56638e4ad1baf74bdb41fa6a631"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "7544bfc25e357a9b2ba7a2c60f943aca02967334c44d2bfcf8232b706dcc67b6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59399480d87904e1c6872bad31c9209e13a8faa1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "ab67be695da9d56cf02c7e74d12c08d766a53d156840d7ef72bd65ede388d683"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29945e15d960fd9698e40cb59a4210a3eefb765c"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "665afd7dd6307964a353d88936b2b0563a6b3df86190d9d7c3643a370cdb4ea5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "813e15872b569aa016ae28e01bff2736e41886a6"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "44f70b6f3252bfd6abbd0e673c61fc8a0de6280924bc12da9edf1f2f9b9163e9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "38f8aff3ec45111cf55860bbc5a37d1bc419d362"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "90a0dc27d31d199c6705d35a6bf00558c1571ff75caa1c2ef75dc08575c11d1e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c595fc3d5906c21459241dcb22d2d3af604e8ad3"
os = "windows"

    [[MLIR.download]]
    sha256 = "8ebf884f07a3546a7bf72eb3a08e33e7515a437da0f5f4174fc7393e8f4857a6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9466e72b4f86450fb82dad6d59fff06126b9a21e"
os = "windows"

    [[MLIR.download]]
    sha256 = "5a7faa2edf511d356ba92c4bb013787044f81caec209745a20248668e52683f9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+2/MLIR.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
