[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2068a65d4c8fd6b35198f7566efa14d4566344ad"
os = "macos"

    [[MLIR.download]]
    sha256 = "c3c7e030e5bc9745f74370c440799a38fb1b78170234af66e5cceab9cfd62ade"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1d39e6a4064238dbf7751bde5cf04684e1cc4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8097eae2c5e964849aec527cadef2c0725805c75e9157999adb55e2803af79d4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff66d997feb96b10a4b08428aff74d01e9b4f69"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "a10552e8f430d0c9ef44b410ac8f301ec97d859eb36bd5c5ac5923ae38503b1d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223490c58a9b298b7ce5f9354e28b665aec2e719"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "13c0b7f57999ab3ffc88f6a6eca156c8b605dbb53260de1c71c7606ae0688822"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599b0c45546d648cbd2102a63899a9f624947d3b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "f6067b677680ecabf1b6a355d85cc31b37b018905aa1b46c7f73a53be78109d8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86239578761bb938f7f65901bc541d2243df9d61"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8f4514ad65d1edfe9f3b2e07ca003d33da66e1cb2b7cbcaea8abf38b88c94a41"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e94953616fb62439ca136f23219e99973cb3c1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c06553bd13d4d5d4d66f7cfa8dcdfe1b1070288458631c5401a1f6e72968d3f9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6406c3cde90ac0ac0e50d83e3e3df605089353"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "ece970fe7ec69921c59397b46feb1e7aa8f305ea02b9ab7b1c8381beeea95ef4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cf0fa9c543ae2d07bf93dce160c04a6ebd2c5b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "38a4efc05a74430f96587e03a511c5d6c05a176751564acbeb5d9c1767917ac4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b44c711c2c85036ad7ef75c820b1872822a99e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "e9caeb9a78b7783144ed64a08ef5f102fbfadb9e19731477065a23990e2a90b1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f270723ccea3487583cf90599db57e55fcdde0bf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "cd5477a16f6336d55ac2467efe6b23f6aa821140c68f290236e2794e1bb78cab"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2f42158f55d9508b6ef627c691707d51c795744"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d0d6172fca7b4890c01b86448154960c1c676e0a5820c9bc2a856b6e66237047"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84084fda385a252379bd63f1a9e2fcddb031d8f"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "73cfb8af69e571c7ac625c9c9247e12cd8c2191a0ef55bdd8abac8402f9560b8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97c1caa65c4a0a6ff89f5de9f1835205bd730ce"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8e45b0f306ff66797feeffb828670c8b11d21d037b8538ebfa4c0f65294847c7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e77ad3e0cb9566862ed5bcd10d002026c407e9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "aea263af97a54bcd15fa30fdef48a9dc51a2ddb93fed60154d1bbc88c889e01d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8cf1cb1ec0b1efa1b92004dffe874b53052f0ea"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "2cc3c0fdeae97989ffd44394ef2b7b0b38bb241303c9ed910601d531579c2835"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2364d5ecb7f828d0e278e148d34a71b56d93e87"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "298b187bd32129702c3a904e36633932406f6a5e397f2deac89c2e3680e5e8fb"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d6f7d160ebb46e98bf411cb166b337acd7ac945"
os = "windows"

    [[MLIR.download]]
    sha256 = "5d815344f39893546dcdc83d4ced30171b385aed5de58eaf4c93e023570d3d4e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e8862648bf3fd71b1e2bcd05b0a1a401699d82e"
os = "windows"

    [[MLIR.download]]
    sha256 = "fea11c5f6db7d4621b0bd77b154430d4d479bbf6f2104de4ab316083a19d3c73"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7418e58cfc6c6c2fa57597999afa8a7a3c4e79b3"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fcac341126968753afd5da97c616caf08659fac0f60255aed7899946f0a4771f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78bfa1d82861a59c149f63f6dd95a892c597a059"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f3d1403625b57e65ab532c18b80ef815f034414d5dc93c7248b843fe8ab58e24"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "42beab69c720ba2d8503707e6f6dfb822a7ff92e"
os = "macos"

    [[MLIR.download]]
    sha256 = "67d7cce45934c85e5570f82225bfd6d46ba8d964f7819920465d8ab59a50568a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "529866c736e4d3dca2fd9af5587c84c9ba4f2b1a"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c342261cc9c262f3ba35fcd4bbfd98cde2a8cf683b17fa5d9e6d71065839f44b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac65f46af335324d8c3e7f46b6274557224d81c"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b0b55925580eefded302df2de07d54aca969e621db87721bcaad16e310b03691"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21701d1b552b8e4749c9d784a7260996520d04db"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "716e53708e275dc345604d989f123e8beb980981674d98173089da95e8fe08b7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6c9ddf26a9ffab0e30230d85db1af4f754635d1"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "ebf6604905cf0c91b1a2c2b54f91ad9aff4a6886df540c8a8a4eacabb492a634"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad39b29c4bac16e361694ac3d6db1de7d6fcd5c3"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "af30501c851682c10489925c66b807989614b4e7db8f35e15c3d5c66c214b11b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b8d19aa2f9bdc48cdb030ae581d803b1fa01002"
os = "windows"

    [[MLIR.download]]
    sha256 = "4fa61d684ba4fec45f8ba7eba7a9df79d0e47266af0661fe4eed5ec02500a733"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "455308ccab01e384eac43ac00840cdd4687b82ad"
os = "windows"

    [[MLIR.download]]
    sha256 = "4a9e3ea907991791d61c01f55efedcd8407c6e6902f6339514bd3eb07af55b7a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
