[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2068a65d4c8fd6b35198f7566efa14d4566344ad"
os = "macos"

    [[MLIR.download]]
    sha256 = "9ce688baa546a3d58240aab81dc8f207437c23e0565f51b698ef9e6785533df6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1d39e6a4064238dbf7751bde5cf04684e1cc4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "eeec483ab42c52b13a617a55c81775a7c1287ed82a6dcf77b37b7c2ed20e8c4e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff66d997feb96b10a4b08428aff74d01e9b4f69"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "e0c410f392afe93c58e537b7debcc051a1d4bb38e2955b13fdc3a5756a0e89de"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223490c58a9b298b7ce5f9354e28b665aec2e719"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "04f5d961f4a5619aac2ef8072e6a927180348cd4b8375e5916a6551e7cb603a5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599b0c45546d648cbd2102a63899a9f624947d3b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9c0c15c9094585552bf5c271f7f22817c7da8ff57c624e5c3177a188fa6279df"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86239578761bb938f7f65901bc541d2243df9d61"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "323da3e169d8b337607ba4ce970b61ce10445f7ff8e685953a168e9b94235ff8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e94953616fb62439ca136f23219e99973cb3c1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b03dd6c737ee105cb83520767b9155b636f86cb0040e008e2575c17972fbe959"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6406c3cde90ac0ac0e50d83e3e3df605089353"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "438c8111342292e07e5b46915a9666979d1be9d4d3c9218229ac277a57133c76"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cf0fa9c543ae2d07bf93dce160c04a6ebd2c5b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "daaf282f1a67532038757abdc45f3bd70d3f01b2ddf2215995c9f227d1813778"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b44c711c2c85036ad7ef75c820b1872822a99e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "5fe30dd4e14c55c3c6ef85e08f13110d79720ac3e02f3fc5cc6e5bc2d600b9a9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f270723ccea3487583cf90599db57e55fcdde0bf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fa6719b2a913da31cb8f1e7dd129359b05c2322b9b4d76a6970b80a86709e1a0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2f42158f55d9508b6ef627c691707d51c795744"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "ac837b553871d132f1393e0b433399597f71058f7630920efe9a54584a1c647e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84084fda385a252379bd63f1a9e2fcddb031d8f"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "6605807ed09d2e564b8a315fb13d41cef50c3ec9df8e3d7adb7766d6fa3129da"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97c1caa65c4a0a6ff89f5de9f1835205bd730ce"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8222d51b7f24c99aa2709435cde2c200662e253520d499d8a092d015dd58640f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e77ad3e0cb9566862ed5bcd10d002026c407e9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3ee46c6e216759f1ceb69141f1d24f663c57944528d6c682085e184954b696ae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8cf1cb1ec0b1efa1b92004dffe874b53052f0ea"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "a558185eaf502671e23b418e40831fe0612f6253edb47f8c6d4689b7056220aa"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2364d5ecb7f828d0e278e148d34a71b56d93e87"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "64cacb45749519c9bbdc9041199a468f884a2fcade3e36d9b6fbc7afb49ad815"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da1fd27bd21a26e81d8d3952e0ef72a1a895df1"
os = "windows"

    [[MLIR.download]]
    sha256 = "baa51cb8b342124238371bfb477b119d0117b6d3ca0c6e955ff0daf9607dc2df"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f751dcb9adf13873787b56a1fba5db3ed2d1293"
os = "windows"

    [[MLIR.download]]
    sha256 = "0185e8a81537cdf44444443022b657157767c38f79573901a0b5baed38cc0a88"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7418e58cfc6c6c2fa57597999afa8a7a3c4e79b3"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2fec29932a9fe798aa58634d6ab2e8ba233490f01539fd04d5c6e208551c52dd"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78bfa1d82861a59c149f63f6dd95a892c597a059"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f7b74b60db15f058191efceb337b5f6247fe3faaf1fb0515a7803c668d8c4e0b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "42beab69c720ba2d8503707e6f6dfb822a7ff92e"
os = "macos"

    [[MLIR.download]]
    sha256 = "d174c527d340ae4dcfe1dd7937daf8487ae87cd7a8ee2f52e1b8b97627594379"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "529866c736e4d3dca2fd9af5587c84c9ba4f2b1a"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f559a7aa13e2766ad445ddd4cef6559201d54cf195464d3755d4ca3ad0bf9e46"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac65f46af335324d8c3e7f46b6274557224d81c"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fa6be151712745b335889e03e337ab4e6c1516f84e27ef2da34fe8f3d01577b0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21701d1b552b8e4749c9d784a7260996520d04db"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "10756a8e738fe6b23369c6900a91ee6e90ac446c017950667154d1245e9ba168"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6c9ddf26a9ffab0e30230d85db1af4f754635d1"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d7d308d42590882804a1e6da909777ea4a37f273025e05bae8d5aec39feb0599"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad39b29c4bac16e361694ac3d6db1de7d6fcd5c3"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "263ff530d9a7d2677efa3ba9433a381bf8dc8cb789224568dafe7cea7947a3d2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "535c46a728057caf4786281939f6035246231175"
os = "windows"

    [[MLIR.download]]
    sha256 = "f988700eb02cc2446bf301addff24458d319d30eddff68f9007a20d5b6e9a47e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8eb1bf96ce6049d4786d347dbedccbdfebd561e"
os = "windows"

    [[MLIR.download]]
    sha256 = "889bf6b5bfb7bfb99e3578bb1323f94d385b79f38c7b28bb045b910cc130ec73"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
