[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "ee764f827c9b23862019e9503051ac11657732ae"
llvm_version = "15"
os = "macos"

    [[MLIR.download]]
    sha256 = "ad8592c60e5d1e707a9847bd4dccd58d1670cef660765fb7ea7c0563adad6144"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-apple-darwin-llvm_version+15.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12e10fbf352ef0797fa5547e5f7551affed47416"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "e710c7e10c7bf6a3974118228740d929f47f1ae4665ed3120044f09463f953c2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8ca191dd019d49284e20a11ac1bb1f487ab4137"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "4d35ed9e9f3ec3a21a6675a3cc0a8db3f36ec5cff6f3c5ebe42f753d8eef6a49"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b190f22eec4a8d0087a734a7fd237a6c35bdbd1"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "2c894de658e363eef49c9bc17b8fadea8a5c3eef2e032f8d38feec6b0891acb3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21b404a11a44100a95bfc827abf5c9a4ff5f0620"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "c441527d98a32dd454533b591ce32820b790e45d0bf2931e70bd9aeea0f7e162"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c176d0f3a153b63a553af714866d8b26c9d68d40"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "b7d568b1a89d3c239af2f7fa844559a5d49a779b529ab888c835d71a896cc6a9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d0073622360ccf96315fde0073b2b099879d3d0"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "7a847ca32438f87ee078b907688f24e9dec71d078f6f8775dead6a0b0e3274d4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e88ec004a799e1d9ab38eaf99f994d654784ca1e"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "e6d99c3ee03a010937daa814bef421b7519aa542c9e6831727a39748594c1662"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae4eabd5a9d3f29e5c17f339eba094fa8192b91a"
llvm_version = "15"
os = "windows"

    [[MLIR.download]]
    sha256 = "1e0f08b8cd46486b7ffa5963092a8acfcfcd7f8ace0ee05527bfb9f101ad945e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b98e0e8f56d0cf7499fd79c023a66ae1a4a97dee"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "024526f73d78c68f4e90dfda40968d4660840e26b700d9494fcc667b99d123b4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "fcb76c649568b2e10c0f0c8eff6466acf3082967"
llvm_version = "15"
os = "macos"

    [[MLIR.download]]
    sha256 = "23ed516a7cab84947c1a0de66f37cd0af07cb6495243c5de05f2b85b6d49ea97"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-apple-darwin-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4ce6bb0aa881662a39a50f4e6bff89c4400abff"
libc = "glibc"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "2ecd231bf18a34f880ac250616cdb0fc08d71a582ffc9853d484d29953b19802"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4ce6bb0aa881662a39a50f4e6bff89c4400abff"
libc = "glibc"
llvm_version = "15"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "2ecd231bf18a34f880ac250616cdb0fc08d71a582ffc9853d484d29953b19802"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1f1a1c2f83453c4c945492b30c90fbd1b24a3ae"
libc = "musl"
llvm_version = "15"
os = "linux"

    [[MLIR.download]]
    sha256 = "3705d4fb20b0b08eb43ef4369a4e370fc586a2701c3637a1bcde689db4697ae3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ae813f9238d001347c3ab7566c9977c1cea8d397"
llvm_version = "15"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "69475fb9a7b53928be73b2bb02bad643896621564790759de16a28c4501f29a6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd0938caac700ce579d97c19f2774ce1740e7538"
llvm_version = "15"
os = "windows"

    [[MLIR.download]]
    sha256 = "c45662108f6e449a119a411450aac4860711cf83a3823bd3c6c3eb89f22c9bac"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "7859ba5b78c145174514edb1f30dbd7edadd0757"
llvm_version = "15.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "b6459b8e3dc4746cd96abd725f615bed0986e5fb2b61d1a0f2ec7dc0454d81e7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b0b9909b3f927ba593adbc319d7177afd90b053"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "ee1fd3804e850cc88066311dac4db0dbecdf93181d6e95dfe313f5fd41d3eecf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef1372cbf97719b4e7e49493be00903ca2107fde"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "ae4e871a80e1b0d9d93285c70a2c012c31026cac8a958fe1e060bf1d17f9fbf0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.aarch64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d4f711832bc5644a5103bb964e500c9b19fce0e1"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "e940ce1a18a8be705a9efec3cf39b74b056d6d032373d527ad38424ddbf15260"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv6l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94fb790f47e415c47d0ba08646289cf527a5b9e8"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "bcb6049f613ac5559096cfd98fb62030835bedb879c795ff70e21a85640650a1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv6l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "277c908d17b334f2e4a8d916f74281e97a02b25b"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "0492f63f8f71115ffe13c06324a5ae806e7c9e0ce146bb50fcf85046c784ed2b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv7l-linux-gnueabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0c911fc4a593ce40f39a834a9d091b6648ac877"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "854514df210c3ecea5a6e0db6bb368d9aa9561af8024dc43412276121c8d68ae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.armv7l-linux-musleabihf-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ec742d6af648cdc89862d1795e98bfdb4413c0"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "01e56e0003be5dcf1bb734c4dedaeee9ab6ce1308309394c5cf4991df7262fa4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.i686-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c88fa8c2e607c18b7df29e15a354fe4c211ec2a"
llvm_version = "15.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "2dd3c131f023c114f1a73e8a9007b6c765eca64768a28cb3cedf49aadb351e2c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.i686-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "39760c57edbe91b39a9a6841349f881f38944d36"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "e546a9abf91c05258c86b65aa90e82f5b57f6506d2b772d5b8fba02843dbe075"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.powerpc64le-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "a24510f4ed50bbbcd23eb4d401cf972e697c060e"
llvm_version = "15.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "a55fd1bce2247248169dcf36314c48b481a75d0576071e0f04a176e48a457a07"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-apple-darwin-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf8abd53c30c7ba429d1baf166fe6a3bbddca04"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "bb5a98bde1cc223a0f9ebdbb8ff964b40acb194e11a63c1af9930d8485c8be68"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-gnu-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1bf8abd53c30c7ba429d1baf166fe6a3bbddca04"
libc = "glibc"
llvm_version = "15.asserts"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "bb5a98bde1cc223a0f9ebdbb8ff964b40acb194e11a63c1af9930d8485c8be68"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a24d25aa0cbddfe18279fa85f83cb143737b5775"
libc = "musl"
llvm_version = "15.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "fc73e1b7f79717aac5e7dd59e3659f391225e9d4a35529a47a54191d5f53fee5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-linux-musl-cxx11-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "d13ff34c3545484a6f8b9e808733c07a49234b92"
llvm_version = "15.asserts"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "86e953e4662d7fa5141889d5facaaa6f9c7268d529c6fcbcde5f6bfa99f13f1d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-unknown-freebsd-llvm_version+15.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f92a279829f957e411d7689d45f3dfbfb6367019"
llvm_version = "15.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "49d6b63673ac66e138a595433188f4625c08fe1dce081856cc9a3131d66eb69e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v15.0.7+11/MLIR.v15.0.7.x86_64-w64-mingw32-cxx11-llvm_version+15.asserts.tar.gz"
