[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "b1f7cd32839f6802f43e6b9e59e03336480c1b97"
os = "macos"

    [[MLIR.download]]
    sha256 = "017cf8847268670c9721d5f15fd52b665df1ae030c609ecdc1fa0f2a31c71dbf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd19aae94f16b1dacc8e98e7c609560f7f0a8f5f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "46a73c812bb3bc32cc556fd3d0fb1ed7acff495cde82f9e0d3ea68345751b0e7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eabeca2aa61f5df1d24b2480a02d6f8c2aba8479"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "1d26565f616ff42659515b06509b3001df366c6e32b6755c62cd149f20452cf2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1bac5f9570f9aa6d95b01b3efd68a1d2b04e49e"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "8e554bc475049fd8a24bb35c53f4e8de642064363d0bad7989cbfa494f24ba34"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71cd7b83d9e62fbaaff67765e996e85a35fcc557"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "373e042faa8d1f9d26813c0299140f6c97c627f91d826804db7626c6bb74b963"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb2976368fbab712a2ab87d5e55231e0a6fd388"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "a7e00bc5ce4d3d4d6bd56a902e83035ee6d769f72fc3f7d96eddb5d4dbc4564c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2884b09ef4166257e8d18482c0221ec5850376f2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "7dbbe9f3a827c26982e0496474eea49faac40341a55bafb5947b71ae2db34e26"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77bfddfebf3deae5f77cdeb6e7c737f34b72e12"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "1963fc02bb22d1b91c22d6e08b6abed460e7595485759839759dc6299aece61e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7728bf85a1544c230242a2ac026df0a17ea58a38"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "16f4467f8d2d04c03d1439840ba2e51f257bfabaf820d6eba8dd170674f35193"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92468b949ca7f783cb620bd98e3d2e408a0c8ee"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "1ab6abb4c4482b0aeade9a8a0dffcfd427d0819aaa7341b7e23307070612cd15"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82fe8558327652a7d3028a4e8920b9f724a12221"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "290d07e4b3a59be666090aa07cd9e3e16c3a10b22686592ec82d5a049f8e849c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "567e8faa596a5d1d11726f8813a8666fb67a6f60"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "e2648fbd758d299a7b64e00c137a6205b1c211f9f57141331c0d36072b04faec"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973db291e58c5eaebaeb42bc0a6fed066fb20640"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "4740a998df1a2ab01c5403387ba142ab155272bb33cec322a78e23761ab09b01"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94cfb83f1d57ff49ddd6ff039b147dd73edddca1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "a8644c88f11f089b14c201d659b198983829d479ea66612ca3cfd4168a950daf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6868870505051db5755c06945f0405c9996857cf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3888d9fce7601e536bf639046e9fc7f58ab5687097a099b015dcc0f87db3870a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "398a7a3d42e2ee42f91a8fcbf3ab0158970e8812"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "e2a7c45dc06071e1394780a2d484af04b1d18c3ddb1e43b34cc7766cda02129b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfdcbeca5553896383e5706434233e1de96db0a0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "61334cc53fef8d929d8b7afdc731fd676ccd946b7d87db6eb59eb39e6f2eb6fd"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7648210ccfabf9396b0ae08371408df0a0e668b"
os = "windows"

    [[MLIR.download]]
    sha256 = "309dd90a5c5df29c3c84cb7708851541db184359e2ede01ce255f95c85e3d35c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7fa4f67cab53d1e8efb3e91aa0ec209abc7e8587"
os = "windows"

    [[MLIR.download]]
    sha256 = "7c9dd673ca26cc57d0febcd72e425d6e85ca07a7e8edf485e45861ad3988e701"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1263166316d30cf8a16825a7e2d01693aa4e4cc9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "0931559d7a7856db1a7e97c7b7ffd02ed2453c09a867aef83e835826f70b1788"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e17815b54cb50ec2af1bad7f6c948350d61776f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "089bcee51a911be229256ee7be9187a6e36e5bbfd0df75a933ed9446bce67c22"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "417369d36810977ca00a5eeaa5c9e2ebf746b91f"
os = "macos"

    [[MLIR.download]]
    sha256 = "c9b169c421068fcef7133b09acc301c5b7c66e1ff7a1d3394d8c27127ffd5c33"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac3e6fb4ff2f56638e4ad1baf74bdb41fa6a631"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "ae401c59442acf72a6264ab11e6198b1f77f415105e869956af2d75ca3c553f6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59399480d87904e1c6872bad31c9209e13a8faa1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "9784588193a2668a529b25bceeb8b01d5d4e21158c3d225e3a28be08333400c5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29945e15d960fd9698e40cb59a4210a3eefb765c"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "6aa72bd952aa9071fca297ff9e6324505cfcfc44be8aed8b02f103f858d276a8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "813e15872b569aa016ae28e01bff2736e41886a6"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "b986298560b21a1a6bdfc5613d06bb325a0157802ae35b7908db47889a70cf1f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "38f8aff3ec45111cf55860bbc5a37d1bc419d362"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "b12a43ece4935f1880173cd7b28b6a28cd4308673fbf6a4142eb9714ed521903"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9267e194c423beee92bd05261b87c0b24aa70194"
os = "windows"

    [[MLIR.download]]
    sha256 = "6d533abfce5bda56f115562e6fb265ca3f8272c65d2634563e0a226b9421c6f8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47e8582f95cfc285a36a218f8b527c40df63b3bc"
os = "windows"

    [[MLIR.download]]
    sha256 = "e12eb58d85be282efbb4c6336bc0f0d0bc7916cbc039a38dca0995e447bd9178"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+3/MLIR.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
