[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2068a65d4c8fd6b35198f7566efa14d4566344ad"
os = "macos"

    [[MLIR.download]]
    sha256 = "3e2b54f2b55c5a7460189b1e2284e454bc1315212726c8ddeb1d9d8bc4ea0943"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1d39e6a4064238dbf7751bde5cf04684e1cc4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "392ed9f923970bc5b235efc2243e108472e4d755f7dee41085dcb61004a771cc"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff66d997feb96b10a4b08428aff74d01e9b4f69"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b039f4a870026a1e4fb016539eda1b1d41800deb4ba6a47055d29242aeaf1dd2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223490c58a9b298b7ce5f9354e28b665aec2e719"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "6cd3470e14368f79402f1206fe06136952c6496576eba0e1c203ef6c7d108f31"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599b0c45546d648cbd2102a63899a9f624947d3b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "0ebb6643386c0825c0cce81869d5bb56afd4bb7ab30e1ac9da7ead0fc5ae625c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86239578761bb938f7f65901bc541d2243df9d61"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "89395cda383805afaa60f30c017011fc697f4568870ce331708925fa90e5508f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e94953616fb62439ca136f23219e99973cb3c1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8b803525a0ad411ab5dbe046721044a22a7b96b9cc061091a0b57a2edcc2b487"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6406c3cde90ac0ac0e50d83e3e3df605089353"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5416c8fc3a998f9eacb94ef37ebf06e720719884d2f46ff48b63b1d6ae27c35f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cf0fa9c543ae2d07bf93dce160c04a6ebd2c5b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "85d81362c8c7ac743affe797b824e9b3c74650c8320c7778ea028052daa600fe"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b44c711c2c85036ad7ef75c820b1872822a99e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "6f5587d428fe24b3cc7428b4c48bd95a69165d34df911146824fe862062bf89b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f270723ccea3487583cf90599db57e55fcdde0bf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8053297edd0c7fbce04a9d426a3548f0720a2f65897e60b53237b1a828c16dce"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2f42158f55d9508b6ef627c691707d51c795744"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "265ab715949bbc7f505e4f740edbdba4fd84ce933abc878b4f3a805593e2d066"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84084fda385a252379bd63f1a9e2fcddb031d8f"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "33e30fd325a283d36c5552190f5556d856be91aae4819372055028ae53f7273a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97c1caa65c4a0a6ff89f5de9f1835205bd730ce"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fc18609bb03f06f6c36c94e44a8622bc57a4071a73d44a9eda2e419d9123aa85"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e77ad3e0cb9566862ed5bcd10d002026c407e9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "dee295e8714b660fb611f5b21bc8dbb5eb40412af1c127c1205cdd10fb08fa55"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8cf1cb1ec0b1efa1b92004dffe874b53052f0ea"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "2b5b87e303d0dedda60525e1b773e62c0231ed233e5c965f54a0a2e50fd79e94"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2364d5ecb7f828d0e278e148d34a71b56d93e87"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "4ba4f682ec7f65bdbfcdd4beef7376ee1f4bbfb2e5b452d863cc8aba2c51c37e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da1fd27bd21a26e81d8d3952e0ef72a1a895df1"
os = "windows"

    [[MLIR.download]]
    sha256 = "6c6e66d37beffa2f9194f5398eaa88d8082c8a70e52dd226b550cd4331bb78a5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f751dcb9adf13873787b56a1fba5db3ed2d1293"
os = "windows"

    [[MLIR.download]]
    sha256 = "914bcb74e92bf9c50f4c17f12c71ace5a520e9f1b648ce7dbe972edf52ab0dd2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7418e58cfc6c6c2fa57597999afa8a7a3c4e79b3"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "9638a17bc3531b14e77d712a10573519c04aa6cc2786e06930dd756a6338ff81"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78bfa1d82861a59c149f63f6dd95a892c597a059"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "96446b0fc0d902ee28736fdeae154eb8b901f8e2079a9e8fd6b274c106a8e00d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "42beab69c720ba2d8503707e6f6dfb822a7ff92e"
os = "macos"

    [[MLIR.download]]
    sha256 = "6489d09b05ce3fdec7ae81392ef0f6a6a94657c58f0c25ab84241ec9044d6496"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "529866c736e4d3dca2fd9af5587c84c9ba4f2b1a"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c1c54cc4d25dc62fdd490b795433ff9990dde0e66e21029b3cadfa80c7e9bf21"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac65f46af335324d8c3e7f46b6274557224d81c"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "46148a31c6d7821216c749f8e881709192f9809cdc28bd31aaf8597c6ade51db"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21701d1b552b8e4749c9d784a7260996520d04db"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "691a9958a57145ab22dbc60fa6a8f9b8d8447dda90738d4bf0c7d5bc4f07f813"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6c9ddf26a9ffab0e30230d85db1af4f754635d1"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "cc0686d39efedf7d611fa7d880e077db3bcdacab0bd08b4ac55f4c38016244d4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad39b29c4bac16e361694ac3d6db1de7d6fcd5c3"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "c47062b43ec282d585e967cec5d582bd771335c04bb41fdc691b1b4c24ce6c3f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "535c46a728057caf4786281939f6035246231175"
os = "windows"

    [[MLIR.download]]
    sha256 = "3b55b22b3c10883793cb2b7481af5cf45837afc210eb8a6d21a5efaca753b002"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8eb1bf96ce6049d4786d347dbedccbdfebd561e"
os = "windows"

    [[MLIR.download]]
    sha256 = "166465703d44ba598a8beb48d5650a1254d27939c5143fab0fd22cc5e9b042e8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
