[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2068a65d4c8fd6b35198f7566efa14d4566344ad"
os = "macos"

    [[MLIR.download]]
    sha256 = "87feeea70af1fe75b7e9b8a3724c756e3f1303ed0d9205a080b855c4d53c3baf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c1d39e6a4064238dbf7751bde5cf04684e1cc4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b88cb369b19fc4adfd8e1591f470508a487d6b861a9c1c6b07791062517436ab"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cff66d997feb96b10a4b08428aff74d01e9b4f69"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "82180255476debc25011d84c8fb86b033b78582b0bcf1bc2dc1f5d835a01574f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "223490c58a9b298b7ce5f9354e28b665aec2e719"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "a7f8a63aed3732ae5a97eabefc6d9337b33717bf6fe84f84de8491da7231ea5b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "599b0c45546d648cbd2102a63899a9f624947d3b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d03ec3728385620c1340e53d1f017e7cbfab578cab3207588fa86d0f459ddee8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "86239578761bb938f7f65901bc541d2243df9d61"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "22163dc8b70c461ef55e0bf46017aaa8ed4bdc99e8c53ca579ffd0c530e12fb4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96e94953616fb62439ca136f23219e99973cb3c1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "5eaa971d62b0828589a706e14e79ca5c71c289ef7e8c00254996f07ccb43feff"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f6406c3cde90ac0ac0e50d83e3e3df605089353"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "8c19bc5ef017d087d6f9264866560bcbe08e4407c589895b40b7f175f1457532"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3cf0fa9c543ae2d07bf93dce160c04a6ebd2c5b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "aa03d368d9d82a46f2aaf5dc61babb05ab4104b01710dfaf4f0c4ff779a6ada5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b44c711c2c85036ad7ef75c820b1872822a99e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "776762a877f0dbdc70a999055aaefa4301ee41011a5d37bae35e570fa4a256e2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f270723ccea3487583cf90599db57e55fcdde0bf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2bfdbd343de30fbad31e4dfc3af0c9d7121b0b077fe26e8b8cf073815301b24c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f2f42158f55d9508b6ef627c691707d51c795744"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "ca161404e38b21a0347067a2a6173b9cd31abef4b3875eb666d545a948cee1d4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d84084fda385a252379bd63f1a9e2fcddb031d8f"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "233ec8b5212d0fe29a5795bfc6488a6586ba24c30d2fa824170b16f1c959ce00"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c97c1caa65c4a0a6ff89f5de9f1835205bd730ce"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "1996d55eb99c3ff6ed016d6758dadb844aaec796c7f2e1c2158b61a261341de7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b3e77ad3e0cb9566862ed5bcd10d002026c407e9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d839a8cceb5ee403235220bc79e8b6edf5a143df761ea814cc2886283db6fb22"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b8cf1cb1ec0b1efa1b92004dffe874b53052f0ea"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "0f53090a4c9657966f9a45603a3aaf89cac200daca6001c0b0fa46f78239555a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2364d5ecb7f828d0e278e148d34a71b56d93e87"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "693e909fcfcb7b56e1ae690440705e4b3d8c495cfea0b185dd7ccc38e4a8f306"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2da1fd27bd21a26e81d8d3952e0ef72a1a895df1"
os = "windows"

    [[MLIR.download]]
    sha256 = "7b14a025364acefe6f07ba82a3b14f77414428eb0644f167cf74077f3e21ab23"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1f751dcb9adf13873787b56a1fba5db3ed2d1293"
os = "windows"

    [[MLIR.download]]
    sha256 = "f2b795cfed0cfaee6ee08e17697972bcc6c9ca9d3f427b43f8f596bed5141dfa"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7418e58cfc6c6c2fa57597999afa8a7a3c4e79b3"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3e060307731226f879dc6ae2f8b05dd7f9f676a0d245b58b511c203fdde99845"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78bfa1d82861a59c149f63f6dd95a892c597a059"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f56de1e62c3c9077cf98f68ba0e0ed346c96bdc2c428dfba492cefae799f44c4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "42beab69c720ba2d8503707e6f6dfb822a7ff92e"
os = "macos"

    [[MLIR.download]]
    sha256 = "fd1408f669cbbd3afb381501febc19f37fa104a223cc8f0dbfda07fde7322e3a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "529866c736e4d3dca2fd9af5587c84c9ba4f2b1a"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "71af4c167d656adba9eeeff6499a4272b11524e8a3c2f534651f37ef1c0d2452"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ac65f46af335324d8c3e7f46b6274557224d81c"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f89823f998bfad5a28f78bbc1e7b0df3b094998465c6fd1688da97349334b436"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21701d1b552b8e4749c9d784a7260996520d04db"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9805d06e94e106635da5f3c03eb9957c1a8ba3792e6725c8596abbc7149ed80d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e6c9ddf26a9ffab0e30230d85db1af4f754635d1"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "c3820f4223ba20b5b444e7c168096bc9ed82f3f71475d85dbf35eb485d4af815"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad39b29c4bac16e361694ac3d6db1de7d6fcd5c3"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "0f8974e1219200deea35bed0a654d7bda38569ad2ce500eb4d633945675e6c4f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "535c46a728057caf4786281939f6035246231175"
os = "windows"

    [[MLIR.download]]
    sha256 = "edcb915ccc936248666817e91c844b5c5b15b2e967710212885892c9260a2132"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8eb1bf96ce6049d4786d347dbedccbdfebd561e"
os = "windows"

    [[MLIR.download]]
    sha256 = "9d2e161e48f8a0351bb198826243b5d40c58c5ce74591fc01c5148338ff87a15"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+1/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
