[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "348812abe7752853a3c0a2936e129eff44b242be"
os = "macos"

    [[MLIR.download]]
    sha256 = "6cdac03191b6f7786ce97eddb301b216ee8205b555663c18dfce900f35f7f471"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b459e26d9ba3473b4d9efcee8d8b4c30e068ad13"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "51493652516eb3cf88277cdbb974bbc10aed4a303839c07fff9053635fde8468"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5610edb14f6fa60f91d7963f2f524c9c5dbe7935"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "25a5a4d1b26d7e480bdb4afbdc6a7f446985f9fbabfd6bba4e5056ec576a8936"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be657bb21a18e7fd0628348fa883456c82c2ac7"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5e1d97de1d386ae941315a7fdca62026555984337683958820904bf0e020937e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68620713191885f77653def51267dec6771d4863"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "70bf15ab80a1f954f3ef229d4ff5fe6ea8fe6c8677b15be5222697fd4145321d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51d35d13874e4305f5f83c7a9264d83b15a4aab1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "ba06b8b0289cae224ea2c10702cfe9d0c5677792d941f0003df6957a8dc76521"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f58d86974e3e503be0986ae380357906fbe6b01"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "4c6bcb0db04cb9c06121b20f5670a27f1e1d3a42cf208a6542b1caee600835a8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebf93dbdbedbe42373a20dfc5a798d2d9fff11f9"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "b325868e3593af294cda8ad9a2406069b80a30a5287b43be842c64282572137f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "808fb0678472fc4fd249ce686a3ce5d2c913482a"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "3203eff81d8a9ff06aa34186a4047ed14fa0286f293c027f6c86fb166030e5ee"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43286f5f1901285eea4e35c050a031e151e43864"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "ac4a5c7346fcfd2be4637ee240949da7578f22af548de2615613a35149f88ba1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4919597d2df0cef2b1759594c047f5dfce9d7b84"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "458a954b5909cb83139617a0d44e74e3b06efe0b01838fdc581d76a3e1768310"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc27b02b5e6d6b34672ca03052906970567a0322"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "095734489a668ff9f7322596ecb0b00e9eaa137dd82189a2cd813a686ffa698e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a94643ca437ceb91df75f3d1b36104145854fb7d"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "090ab484014e19a375e88ebef9b21fdd67bc106f6e52654e581ad193dbd399ad"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "581d341c7ea632d1bf47ca6220042137a23d5461"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d45f6057466c525a1fb3994eeb76aa0ab3a622b096bf38d928031a249e7a8d4c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5685a001623851c717e2b14df979cd8fc3cdd5"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "9aadb5fa3ab32e2c714a95f225df03dc9edce11196a6e5d037ac32a6c6473e00"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64482f8b5fced693696af98cd18ab6b73cf4864b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "af265d43755b94d039811689938e240d8cd27ac006c140d4db65e8c956296f0b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d493a374ff22fabb1cc220c7cddf5bf197e1443"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "c8d3c87424616a0e9e5d81a50f493a25c37ddb527148d06301b5835758daef75"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92857b4c3877c359528904d0984c594c6749ec5a"
os = "windows"

    [[MLIR.download]]
    sha256 = "dd7dc338ab370209a6a5a52e4cf7e035bf855232a429a80cb5df5eb6b0ba5ef7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08a5e329a041f783c24e2955fa2f03f253e19982"
os = "windows"

    [[MLIR.download]]
    sha256 = "1b7bca851b7674e0a3ae726a3cd47b409313a8b32c5176b0e751076064d00c70"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dbcac6c220df7abcedb6408b70fd6c850939056"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "a8c43dcc73a57370c36387c1e75bff1c9d76c78cf66a32a8269907b45e60cb91"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccf0fbf43e5491216420e24e8a0e818e4a0dcba"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "47e5946f003f0fcc55f20d5a99fa3b8c079324973cacb112e4975e22ea20fc61"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "c08b9fe5d14268016368f5a28e4a2821925c3b17"
os = "macos"

    [[MLIR.download]]
    sha256 = "3e706944d8ab5f187be647d59d8316e1bb2ac6301cdb25706549a96f24b39fb0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a90561d99d58848d47811082955c5e8951ef4fe"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "4ececb8c3889583dd24dc3054a9bec3668e877ba92dccdf09f7a0353e4a4f6b6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fcee0ed6704f92ec1e50db15534b31c8ba9f98b"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2dd2d6fd9fce45ceb3ca025f4bf5950891d77d910f92454f1c277e280a6f03f7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "585451eea41434508b48faf0fba550b4959e41cd"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "595e842f9a52c7abbf1e46bcd41323abf7a11ff0266a503503fd9f537ff49dda"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0429a1a285c646e8708422d27111eeaee8236ca0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "fc419cf30ae72f2fa298b3afb960e7f2b97a3b7578f117d171377a2bf9049f5c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad794920c1069ad50493be242577f24d542d1cd6"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "9be400ffbd58e51ed47f9ff7f654d9a4d5d2a2f1e71809f4b48691b00d8d0365"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "528f67a219d787742c8680dd309eea01d0fbf030"
os = "windows"

    [[MLIR.download]]
    sha256 = "34684232ae85a727a835783d0c8c4e184385eeee33232230462526c924e48daa"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca2df5f641b78c98b1734838fea3851ec28326d1"
os = "windows"

    [[MLIR.download]]
    sha256 = "742d70d239e397ba2d091139eb5b53d28970f417e70e4e60c4185b5ad321b68e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+3/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
