[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2e7d8fee66bea126dd18caa30eccea2697640f9a"
os = "macos"

    [[MLIR.download]]
    sha256 = "2185ce3b6390db20fe36e5c9fc3c5fd1f1450efc7d7734d2a99d0ab4f6f51693"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84a22f0b60262982146e0e26053905c31b37e022"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b4889844f6d67ce4b8e6f27b88c33ea8fe66af391983e0770849a9ea2eb33c7a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11c372894e4157e152a58910d8a4f03296536cd9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "856e25460171b11850c4c4285b995df1f4b1ec030495df8936c0a9ed6fcda955"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3664f4b977a4613fd38c210491b77c2cf6751495"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "604b9b87d42f8822a60ac224e129a5564d98801acbad25ff659153a08e203768"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7ac70481be4737d4440fd2d5ce7af56c2b8e1c7"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "3fbb3f509fbb51d51d1563ae87159ed7518982bdbadf72755076d1c1200f6d80"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90401409671fe73286fd7bd74f79ad98d11857bd"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "5661b6d2ed4964e7bffc1030377387be6afa125f4b9698ef6f2915f70ad9071d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cfa4a207be47a6806376f856f9bb9f6e2df8ffb"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "dc57a7c2bb15f397891a6c34877125094633f25452db96e880a324d7828e1d49"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32c47ca60c7337268ab6424fa33bf625ae05de0a"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "63880b77a25466bd58e10d24cf6e1c62827fc37f7451ef3ffd262902433c8c7c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dfc127530855c291263c95041919ae8b83282ed"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d2b556562d9e3f69587070935d8077f804cbe5ceaa33acfcb7fc141523e298c1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccaa4336dd22e36c2ef17a500f21934939b464a6"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "95136a98df90fa56f3c90390d999dbf08a51ce7fc81487b3128ff4f0f016f356"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3001c53251698a738aa26636fee186df3bfb0681"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3f133cf7749b5d7a5ff881dceb3cea2100d449fffb6771358759f4dffc1ce4e9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a70a9df05f2e25e42b393ed5d52bda4e9fe28525"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "3de7c474df910a7ea7537591a72bc0ae0eafa815f225a983fb178591e216e123"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5880cc02b2633f7d8b9a57469f8552a5c73c0ec0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "6cd561bcbfd4c0d53b38d9805c3485320d1eab8e7865c8593f9daf476604a873"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d38fc0adf1a357010497f1080ceb3c6760550c4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "7fd27acb5137c8875057fa1e599e63d5fe45cc472590bfa7761494748ddf6367"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f22d195441d1055405bb433e46dbf07d282b6909"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8e91e0e422bc14d09000d19dae6d1934791219e081f33f161936c9d117359706"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aef65dbd47e765bb356e5600bc6007aeb3b66515"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "4048d9f75a590a166945aecb6a359e82510705bd9368c97b7e4ecb1249189864"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afbd95c4df0c577db77e2393e9b032fe3c1a9b3d"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9416970202c21ee77f9f5c4738e57e406548ff895464727c0c6063e9cc5b60be"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc797cc88baa0d9e090b51a6b63a958cebd4fcad"
os = "windows"

    [[MLIR.download]]
    sha256 = "440051256ee5fcfde3b4ad495a0ac68db9514fa7ea0714c1e09773a25434fd96"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53312cf3efd8ba4d7972bb623655b5b933de64fb"
os = "windows"

    [[MLIR.download]]
    sha256 = "7c28eea971151a5a9f0e67a87d16d8fa79b9701c30579f9d90e7bae1cbbda668"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7decd03fdd4c9822ab877c5c7515915deb66d238"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "37952a07a3a8aa2f8f0106352e146e5c620e64594f60cd93293f2dcd64448d45"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "751ab3fada67c7ebcc96141832cf33cddd461c00"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fafa969aa8a19326f2003caae7e5b0409655fd708c71fd7a6b09578499fe3c45"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "bf2da5acf1b8e850e89c5938a9a6798a2ed8ce12"
os = "macos"

    [[MLIR.download]]
    sha256 = "03b3209c81ab643e067973b0320412143783b450050b34be4355079713fc5f14"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57a0e30685aa5d79093fb325c014358498a27faf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "6a503f126e492e427fafb3449103b26f2dc43c1e47bc52fc140531f9ad21cfdf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcaf4daf65f849554d707acf03560e0fd25c59a2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3678152507109d9bc8e6d9cb9ec69989e85adc99bc37a0fa0be39410433fc98f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7611dfa8558a500aafb62b31d03e88bf76dbdca"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "77be9c00c484f465e81de2cebd60c04a09a1ae73439e8873f8a03cb5331710ae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35c81b7044cd43d758d26687e62bb7c3739a5acb"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "90dd6d477d27ddca62c5985bb948e7bbe532ad753ae0f1954de1af27d8b7ec22"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "81a3df9f0c08d0416d7fb87cd7ac1854b7e3fb85"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "767f21a334b7396a29c163bb5d57e3f1f1b6cf6aafb301c2fc184884636cce1b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3153c941eee8568e39d59ac8dfe3ace1d90df4e9"
os = "windows"

    [[MLIR.download]]
    sha256 = "1ec034bc834291baaea01c3eb3c883f43298cd45abf1527dd872a2559484c614"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2b4e2ab7d71281aade797bdf0ba899e318f0d90"
os = "windows"

    [[MLIR.download]]
    sha256 = "8d6faf41740131042868e8bd19e89d4696b463b62224b575c9ac408f7b6c4f27"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+3/MLIR.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
