[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "b1f7cd32839f6802f43e6b9e59e03336480c1b97"
os = "macos"

    [[MLIR.download]]
    sha256 = "2bfe455af8715b31bd5705a5b538b562af5eb368fdab7c5cb80117f19530fb80"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd19aae94f16b1dacc8e98e7c609560f7f0a8f5f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "44f6120793f11f76b0e15e67daa60b1709f0a90e7d6b940acc38d376e7bac673"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eabeca2aa61f5df1d24b2480a02d6f8c2aba8479"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "e85047c287ccf27b852eafa75bcd83155fb2a7f9f9498dad782276a8f437471b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1bac5f9570f9aa6d95b01b3efd68a1d2b04e49e"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "e76ccbcf83ef07bda65efcb1dc050f6549b13cb7a00a4729f47283e43136b30d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "71cd7b83d9e62fbaaff67765e996e85a35fcc557"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "f6bfa2d6dc570fcfa2f78229c27f6ac602f887b75fb174ff984e99caa3d45124"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb2976368fbab712a2ab87d5e55231e0a6fd388"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f3ec27b32a89deb2e0e26d3baf126bf90b6c5e4b9f67b0c1bc8fb3ba531a788c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2884b09ef4166257e8d18482c0221ec5850376f2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "e6dd6f3f1b608d637f4ebc332bcdae1ae389e758e22bde1d6d8f19e2059a82e2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b77bfddfebf3deae5f77cdeb6e7c737f34b72e12"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "c3eb65e96a50d1c23bb75c5284279999c680497c6282ea2925087f8a66aca00b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7728bf85a1544c230242a2ac026df0a17ea58a38"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "a74bf2a7c25cad7a89d873974439eacff8db0bc7d42fdfc75f4e527cffe1537b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92468b949ca7f783cb620bd98e3d2e408a0c8ee"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2a0c891faf56ddff11ac977a22cbe9bd442e8f5ac9331ff39b2ac086b9d0b73e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82fe8558327652a7d3028a4e8920b9f724a12221"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "09115ec1b9f8fe2cec86b69d9368a961d2609c6eb54b8d3912fb0d0b847db34e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "567e8faa596a5d1d11726f8813a8666fb67a6f60"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "0804ede00264e976bc1aa618ced4aada99277c6c10cba2c74d00a46f86e322a0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "973db291e58c5eaebaeb42bc0a6fed066fb20640"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "fedc8dbbd703195d6a35d1c875db3ea41f5bc0a4d674e929c4e3b8fdc8d637b0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94cfb83f1d57ff49ddd6ff039b147dd73edddca1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "72dc34385e23e0db3bb11f51bd6c04752a8bbbe5fdfe897f877f1c69ae2318db"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6868870505051db5755c06945f0405c9996857cf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "fe2d23b86e8783235d5862387f20369356b70ecc6cf6e01b44900f9635bf4855"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "398a7a3d42e2ee42f91a8fcbf3ab0158970e8812"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "b0a0a62deef33efcb9e65e6ad81884727555ace85d6cf462d96578dd581dedd2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bfdcbeca5553896383e5706434233e1de96db0a0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5dc8500f1514913410214b3428cd39d9b1c1c1799ed826cd346f8522a5f3bb87"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a461e469f407a12f66b16449c1169964594d3fe"
os = "windows"

    [[MLIR.download]]
    sha256 = "629330f1b3c587e9e01c22c588d90194ec53dafc5ead6b56479bb13801beafcf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d346bb34664ff7279cba79847c2caadcffd23b1f"
os = "windows"

    [[MLIR.download]]
    sha256 = "3f16aba8c01fd4f70644b19f138d642f5cdfbebf2375867fb4361efd911f965e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1263166316d30cf8a16825a7e2d01693aa4e4cc9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "0fd07e1a3d41e02a9c7d847c649aba6af1fbc33e3c03f38ba86dce60e63977d1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e17815b54cb50ec2af1bad7f6c948350d61776f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "29fad9e89716b4a95981eaa2c918812b260cf7f040336c0e0058217dedfb37bd"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "417369d36810977ca00a5eeaa5c9e2ebf746b91f"
os = "macos"

    [[MLIR.download]]
    sha256 = "0ef2da53615c8f123b623909cb61277912124018949bc0d142be3c28cb517c58"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac3e6fb4ff2f56638e4ad1baf74bdb41fa6a631"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "96f03ef42313290fe219465ebc40537535a8fc815263a80a25a440cb301c95ef"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59399480d87904e1c6872bad31c9209e13a8faa1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3f4ca8a33537d12983a840747205de2dbffd927c13801bfca1121b0f77cbae44"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "29945e15d960fd9698e40cb59a4210a3eefb765c"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "141eec758ff78e8d136038ce9484744af722208cbe1cbf46d30d28f5a2d47ce8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "813e15872b569aa016ae28e01bff2736e41886a6"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "f795c98c4af67d141e55eddb5111750a1e11c9a3c88e31c8421ed45cdcc3bcd6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "38f8aff3ec45111cf55860bbc5a37d1bc419d362"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "473e3a2506b46f7751d72614cc05ce96f626c78290f12ba7384bcf40d032c8e7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "639606811a58350f4504d9d3f9e2968c38908c74"
os = "windows"

    [[MLIR.download]]
    sha256 = "9056e3faabdffe75e9dd624f2c053e741ad87b562bb1fb14cdcb56d617b5461a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a0118a8b83bb887583d4c4b1f3e6573e9e6eb29b"
os = "windows"

    [[MLIR.download]]
    sha256 = "84ff4a4891eb2265504ad7725e72fe3bf9c08b6c9eab52fd35dde4804a14a702"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+1/MLIR.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
