[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "bd1ca9b476616fcf2cd7496dede9fabde6c6419a"
os = "macos"

    [[MLIR.download]]
    sha256 = "0ef0c7af035fe31facf3dba501058077f70e0b4d586c80158b848f38564667f0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd19aae94f16b1dacc8e98e7c609560f7f0a8f5f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "bd56df0aabf4a7da2654518bb682c1c0f033fe1bf0969a7ddd5e04fca065888b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eabeca2aa61f5df1d24b2480a02d6f8c2aba8479"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "04bf5e433770401d5857b552a38862a3636023a9e095bf84c905cda39df7cdca"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5bec9636f0f5e9cbe4b90f5b4159d957ed9652f8"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "09ff147508b056bfd5c2e78f074b1f4701ba923fcfa1f40199215ea552244d09"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc627b8fc8d42e9440a79f30ad5e0588b61ec2cd"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d2b54fa018a066ed68c725706f1a49638023883e2fb1bfb41794c8e8e80045a6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bb2976368fbab712a2ab87d5e55231e0a6fd388"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "4aa6b7a99c5700710185fc67af5fb82f61675e8c75cc2f4e36b376233e689060"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2884b09ef4166257e8d18482c0221ec5850376f2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "9d8084e4cab56a2c8de79fc99bea5bc292263867ef349d7f601eec5d7d628713"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26663902f336e7dbd9293b2fe9ea8109fa16f1a8"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "130a4d3195cf9ab36f561ceea9d621becaa926dbff926ab71a5d1131d36e80eb"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9cd1f18f1ac1cffea491f8fbc2bfd46714a624cd"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "2160089259a844331b5cdea2d2e5175f7f1d381cf9e25e314b28a41f5eb09917"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c92468b949ca7f783cb620bd98e3d2e408a0c8ee"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "0f48b39c012ead64b85813e47f89f4012bca24cc5e7fc25cada1287b6d72926f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82fe8558327652a7d3028a4e8920b9f724a12221"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "1dc966e6e13b25444bd9b3880cab90a858878e86d50b44f11ba882cc2ac7d4b5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b95ef1e36d719e17737682c3dc82fa0faa53d50"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d419ecefa3146f03e47ebf7ec8344327fec92f83dff35ca788b7afdd788d3c3e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d58096cac755c31287ab38bd09c62b82e15f91d"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "f665a2944313efcd3ca47cda9ba0721b985140b303267b90984c1c003127b33a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94cfb83f1d57ff49ddd6ff039b147dd73edddca1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d7f5f9026fedfac37461faf6b4162d8be6876f0a9adefd11819c647c234a6c4b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6868870505051db5755c06945f0405c9996857cf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "a60e56411c817698b5e434d30b56f68f67ad8d0c80a8a40339d5d8c39aaa1341"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "525d108641db16c5c33e38c4d7214d251c7b8d2e"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "53acf384439f505f11557694825d061e01f81fabf3430d30efa3fa107c96e7fc"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d65b16e89312c9dbeb99cd05f095ae6dcad69a6"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "e2ccccebec2ddcf04b8f4007e77bba1e6453f5e3a45b0a8031f32681fe849850"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dccf4655dce56ca59578cfdae50f4394c382fe93"
os = "windows"

    [[MLIR.download]]
    sha256 = "d709b22c6c16beb930bbadf67d0570068b7e74a49ca3b8babab5710fef6630a2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b324dbb4c0129daaa8924c2a67f51a753ed3b2fc"
os = "windows"

    [[MLIR.download]]
    sha256 = "3e839466d3cff1f3fc2da8999477364dcd222fd36d88f601d239c8880650ddfa"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1263166316d30cf8a16825a7e2d01693aa4e4cc9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "16fca08a42ce82fcacc5616f35dfdb31e73794c7dbfeaea453a6703c917747b8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e17815b54cb50ec2af1bad7f6c948350d61776f"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "f9a9a79cd5d444966b897a9d47a647ee645430bcc30ad0229dcd89e1f5b9a3ae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "6cc0a54b87e857194b1365ad4de875ef150d0510"
os = "macos"

    [[MLIR.download]]
    sha256 = "ec6f86affcb2087fd95b23fa84529fa8ecf1ab6c412e6dd393f52376c7e0fd3c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dac3e6fb4ff2f56638e4ad1baf74bdb41fa6a631"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c6062a4fa77970590ddcc742d2270b69258a5b6010d9d0e8671baabaa0c29b27"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59399480d87904e1c6872bad31c9209e13a8faa1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "6e338b02409cf0ccdfa2fa9fe3a8f84ccca8687ae7c72c0b24d3ff1e2ac0afea"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ea0731906071a1feeedb052a7894e113fc55766"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "431ec7414926668a3413af4a5f7df75153e8297d5d30f4f01b4ab234df8e93a8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aec1357065a154c3cb836dbe1c1503773bc2640c"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d196650352de4e8308d940b49b3971a477cd7648f97673d87644214fbff149c6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "38f8aff3ec45111cf55860bbc5a37d1bc419d362"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "09deedbd1ae10eb0037f18f660fa02a7d9b0a1d611e849f2cf74501723f998c7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d083a7dc26247907b4427451ca3ded8d5f37261"
os = "windows"

    [[MLIR.download]]
    sha256 = "dde8141556b183835eb2fb700709e121f275829b05e77858869f5c82ba6107de"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0bfc80761ff360f37142c60bcbf4476329ec05c"
os = "windows"

    [[MLIR.download]]
    sha256 = "07cb978f5a1b91460a5e00e269088aa39052eaf64d674159c98978799173f0b4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.1+0/MLIR.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
