[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "2e7d8fee66bea126dd18caa30eccea2697640f9a"
os = "macos"

    [[MLIR.download]]
    sha256 = "caa50f01b41265cf63f6aa924c7752ed4efdde93be8a521b02c42c79c6899a50"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84a22f0b60262982146e0e26053905c31b37e022"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b22394bb694c5c2f9258a947ac3747cafe8b5b0a68cf4f5168c93cd635aee5da"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11c372894e4157e152a58910d8a4f03296536cd9"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "e2a960989444c167022c3e5d0b1af3a3544f2228cecdb506c4fe20fc91ed0f83"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3664f4b977a4613fd38c210491b77c2cf6751495"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5cc8d8ee39e3b3a59d4dc831980d31e68bcf10b164a30802184c310b78d61e45"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7ac70481be4737d4440fd2d5ce7af56c2b8e1c7"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d8fc76ff3933d752eb13c97505f42c0377109d8ae455d57810ae3f46623ba423"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90401409671fe73286fd7bd74f79ad98d11857bd"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "14b292d2767f4f81079aa2cce19d23946456f8935ebc18b7851dd985e208bafd"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cfa4a207be47a6806376f856f9bb9f6e2df8ffb"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b6d903e296cfda05d79fb4ba24b331c6ba9ca881294fe97148708e93bf75cfb7"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "32c47ca60c7337268ab6424fa33bf625ae05de0a"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "d32aac1e4399d9b03cae632882ef473f6397587db15b2f2275060f4c7cfb1b9c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0dfc127530855c291263c95041919ae8b83282ed"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "55c853cd703ef7b27dd152a9f5f6120355b089c21edd659d8276350e8a2fea7f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ccaa4336dd22e36c2ef17a500f21934939b464a6"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c4aeac3d664e662b44e8145bd8add1cf1027d3571d970dbc8130dacb6e215a38"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3001c53251698a738aa26636fee186df3bfb0681"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "0832b6eee2656e60cee801a4c1e3e9c33c572adf6f8307a25c02668ba138fba9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a70a9df05f2e25e42b393ed5d52bda4e9fe28525"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "34e7e99a47fc3b09168f6ac1670bb84d809b35028040480c273fd2bbe4567b3f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5880cc02b2633f7d8b9a57469f8552a5c73c0ec0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5df77986f53b3195d74cdaa071a543e24ee5047130ba130312d2deca86494bed"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d38fc0adf1a357010497f1080ceb3c6760550c4e"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "74106c5509ba6c3d3a9ea46e8fdd443183892a291cf07a287efbab1ac84584bf"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f22d195441d1055405bb433e46dbf07d282b6909"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "7ce58b1bcc014673dd2b16aa0fa85049900db2e460f81017ee17520a3c27b097"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aef65dbd47e765bb356e5600bc6007aeb3b66515"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "26e4fc8586d0de6a46aca9ff8ec741ccc56e896ae8c4056dfcbd8714f9dbb906"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afbd95c4df0c577db77e2393e9b032fe3c1a9b3d"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "de100c3da9bace7c4372632dcacdadf53d2c085668b8f4668ee5788a31f5423a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "acd1070171991fb6c80f3de61d45bb73eabeb2bb"
os = "windows"

    [[MLIR.download]]
    sha256 = "cc908a8613ce3847ab406c9f65732513c96cf2a3c04b6f5b262d2f4daa9ff070"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "217997aa2e82707ba36254fd9fefefceea3c1f50"
os = "windows"

    [[MLIR.download]]
    sha256 = "9a98e30597381ae54fb08b6a0666e1f5776b550e9e3489acd47b347b037f79e9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7decd03fdd4c9822ab877c5c7515915deb66d238"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "97532e02a9bccaca20606f601b16a206806243b3a0e581473b6c2e1fb1db48fb"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "751ab3fada67c7ebcc96141832cf33cddd461c00"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "97fd7e1f34eb426e83f389b552d947ae29b7053d36d936dc58eda1d86e5b03e9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "bf2da5acf1b8e850e89c5938a9a6798a2ed8ce12"
os = "macos"

    [[MLIR.download]]
    sha256 = "547008d566332cea8e1a1123b5791ac8788000f263ce4422b9d719db9d0c939c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "57a0e30685aa5d79093fb325c014358498a27faf"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "b4c35ae6236c7226e70ea178e28f6e3ea79ba477ac087206c052f9d72b0a3ed0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcaf4daf65f849554d707acf03560e0fd25c59a2"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "7d862b282bb6892ca812cdaadd2589e0fc4aac714a1d0d6607d3fb656a648045"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7611dfa8558a500aafb62b31d03e88bf76dbdca"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "5e086e06fe30d12fb2d75637e4484ee61b6c23db1c3396195a0477a48cb0b223"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35c81b7044cd43d758d26687e62bb7c3739a5acb"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "8dcad93bdb5b02121829fc5b5b7195bca6d701a3cb3af2090e3328cc403d5992"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "81a3df9f0c08d0416d7fb87cd7ac1854b7e3fb85"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "6d7f71e7c99f37611d02086cbfb4015b2ed777609295c2f7b35d58c7a0dd2abd"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e24d6d8b4d4ed8d1904305f90f80e8db1719fa7"
os = "windows"

    [[MLIR.download]]
    sha256 = "aa50e7fe1d7f61eba50635c49e1b6f01d28b22651b8fc979174f1bf7133d9d41"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bbfe699f98147639758ad78e4e35b65304d7244"
os = "windows"

    [[MLIR.download]]
    sha256 = "5398feac9519a42930ab6b5df9a5a71a5ab2c106751ad254567a8b1fe3d7ad78"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v13.0.0+1/MLIR.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
