[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "348812abe7752853a3c0a2936e129eff44b242be"
os = "macos"

    [[MLIR.download]]
    sha256 = "1cc508ac5f7e71b1212deede9ca699d03f1d9989ae58e9cb58e97d4052d84206"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.aarch64-apple-darwin.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b459e26d9ba3473b4d9efcee8d8b4c30e068ad13"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "2fe11f1b3a7931a2572830d32fff744b36d2a949a02ce3857f782ecb2642e35f"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5610edb14f6fa60f91d7963f2f524c9c5dbe7935"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "5e3a755c1461865e957906ac23142502719cd4034a74feff39224bff59dbe7c9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6be657bb21a18e7fd0628348fa883456c82c2ac7"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "398121bb91cfe9fbe0f7534bb227c8b2892a2eb6f214f7f071e903788e875bc3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68620713191885f77653def51267dec6771d4863"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "48f1274334a0458afb2c14c6a8a9d6a7b88b53190df00df2fbafbb874ef3bf13"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "51d35d13874e4305f5f83c7a9264d83b15a4aab1"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "248523ae441df532cf8e14eb9c7b87be7b3525abaf87c3f3266beb8970821ca0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f58d86974e3e503be0986ae380357906fbe6b01"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "11e2978c2b852ac318e3c44c6c39a9c4c9aac4766c5a1d8c31fbc291ae6517ec"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ebf93dbdbedbe42373a20dfc5a798d2d9fff11f9"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "c6b991ae3bbf863552324bde1e75f4779d9c7db5c90864ec16b1d894ff0b57e4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "808fb0678472fc4fd249ce686a3ce5d2c913482a"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "e83dd43f5d7e63b9a9ef28ed6286ec6617db97c73d56c0b853f4dbc859dc78a6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43286f5f1901285eea4e35c050a031e151e43864"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "d2b52e322dc0d6bcb972235fd0b1f9909622b612bf5e8624b8dc7210a0a6bf47"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4919597d2df0cef2b1759594c047f5dfce9d7b84"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "6cca9f99a4cee10de8132387bb209e1ba192566b3c367de925509c370a08ffe1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc27b02b5e6d6b34672ca03052906970567a0322"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "269d93ae61aa73d220508fe997b554575dc2e73efc70cf0404f176971f273191"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a94643ca437ceb91df75f3d1b36104145854fb7d"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "21a0a88be14089f0eb416dd3470b3a477474ae22ed224bd5395248ba10975cca"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "581d341c7ea632d1bf47ca6220042137a23d5461"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "af8deba3d0a13a708520b32801e6eeeaacf2137642ae0233cbd0c52a59d0377d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca5685a001623851c717e2b14df979cd8fc3cdd5"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "870856d47846008cbfb4233013f09ec73261b0e15ad88daf750d81dc177f07a8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "64482f8b5fced693696af98cd18ab6b73cf4864b"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "83c0d85f32ea53df12248733bb0da453187acb0e4e14cd52d36eefdc86e0bcad"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d493a374ff22fabb1cc220c7cddf5bf197e1443"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "1b234add2a48890415f88eb345b2f63020fd5b88e77240df4d9f214a3401744c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92857b4c3877c359528904d0984c594c6749ec5a"
os = "windows"

    [[MLIR.download]]
    sha256 = "38b996a52986cf436094137a46387883502796a881a5ea73cb14414dd13442ec"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "08a5e329a041f783c24e2955fa2f03f253e19982"
os = "windows"

    [[MLIR.download]]
    sha256 = "40b697f26c14737ebaeccf7e11c4402730caf96fb3f92ca60a50ea1ca76e12ff"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dbcac6c220df7abcedb6408b70fd6c850939056"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "90c3061d1b65abf624312c2132d3cf56aba46fbee373fdfbbe1341b077a8301b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cccf0fbf43e5491216420e24e8a0e818e4a0dcba"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "3084f4fda95d65b3be7f4e7b1ca31ea7cc40895869d9fa092cddb365d501c021"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "c08b9fe5d14268016368f5a28e4a2821925c3b17"
os = "macos"

    [[MLIR.download]]
    sha256 = "bae0eed478511cff6adc4b4050109ef156159ab2a2bcb7f6ec19ad2ea2c53dae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-apple-darwin.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a90561d99d58848d47811082955c5e8951ef4fe"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "8528f00b46431eef18052704f7b88f9c59fd829a644e0554947848ad4fa4a8c2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fcee0ed6704f92ec1e50db15534b31c8ba9f98b"
libc = "glibc"
os = "linux"

    [[MLIR.download]]
    sha256 = "c75bc62a7c7d7c554149e2aa533383dc473842f9821677170e8a5f8128fbe351"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "585451eea41434508b48faf0fba550b4959e41cd"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "0df5d9166db5382741baad2d6f81045105d4b40d8cf80d7bed938ac5d54f9d6d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0429a1a285c646e8708422d27111eeaee8236ca0"
libc = "musl"
os = "linux"

    [[MLIR.download]]
    sha256 = "9e907d85520f75e077976c4b1215c822a7c6b49b9c1acbc39ca2a69319aa590d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ad794920c1069ad50493be242577f24d542d1cd6"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "bcd63ba326aabddaf6782edb2269eaac48467569d926dbdb2215b594c7e6f52e"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "528f67a219d787742c8680dd309eea01d0fbf030"
os = "windows"

    [[MLIR.download]]
    sha256 = "e669148c883d6af85197d7d691181d2f2025ef29a9a30ab711e5748d284b01e8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca2df5f641b78c98b1734838fea3851ec28326d1"
os = "windows"

    [[MLIR.download]]
    sha256 = "6db0594d70a9947045bd22787bced339c165b7d50e697308b1648eeeedf2770c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v12.0.1+4/MLIR.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
