[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "29a58886527da57b648394f29d1753e9d318c64f"
llvm_version = "21"
os = "macos"

    [[MLIR.download]]
    sha256 = "33abf3d0ed7b3b43d1253b659e175df34911e49f89a3a9493e267d8d4d64ea4a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-apple-darwin-llvm_version+21.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d07efd6baa004f01ff0ce5ba83f6108fcbb8627"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "675a011368d64f834d5ce175e5b59d68a9d213fb508270f9e2e38e8845d0f9c2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5ebb0db7a33fe1815f5e1bc241c08997182c0d86"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "fc9f9e2fa85d4f272e72c84bde5b80e727f78277ac289ef8bcadb3e552197663"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-linux-musl-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "75fa52fc5903734dc72ad7e35a2749956109d4c5"
llvm_version = "21"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "330addf8b125c5671d71949cbe999bc829b5c05a7f266125a110d7a02c5d54b1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-unknown-freebsd-llvm_version+21.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952c55265d5b7f91a089d3fd5f2793f58b7279f1"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "f9c3d5640939ee9314552606e4aa29b8f8388e9b18b965fd8d520eb3eb111b43"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "815ac015c27f6a32b194be973ab920bcf8905621"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "31c99fd5b61cfc849699aa2f76d0d72869f208fd26f17d52135ca74edfe9b8f1"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a186e8646768a668c41270c8cb486e8cebe0da5"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "e6daf870612bfbe489b71a8a26e8899cf0262df00822097efc8f8ee856d7fa0b"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6fa88b024c1481c6ed60dbef0fff027587a00792"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "02a94fec2f9f6acdf43a9c64f70e1b5bc06977bf281f6a486e71f673811a6ebc"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88b3b0958c4281837cafda2681362140c8021d74"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "ad9ed267d7b9945b0ce16ec1e9f25a0b2961963779cbd378af5d94ca4ccf1d94"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.i686-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c0951a3b8f8b98984111b523fd26a242bb6feee7"
llvm_version = "21"
os = "windows"

    [[MLIR.download]]
    sha256 = "cb6ea7e64b735c7132fa0f0a3ba9670cb2c2ebd53293e1d589d40c082823c111"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.i686-w64-mingw32-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7056daa4622ffb8c2508c5a4fe4b06025fb12b52"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "0d7bf19d5f633223ab66399d758f3784c4e154f9f865b3187acb0bdb63cb9856"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e5af73ab75906d12d8eaa2a33f88224732199f34"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "1fd4fe5ac4ea21af6b86411641ffd63b4bc2498429fc998b1202652940607896"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.riscv64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "ea5fc9744f1e924bfed2216921ad4bb66de73fac"
llvm_version = "21"
os = "macos"

    [[MLIR.download]]
    sha256 = "435c6add14ce8f3ae3541de662da12bc4069cc918bb38b4408b17c489cb464bc"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-apple-darwin-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1d97605bb35cd0993d39de0e488b9273a231eed"
libc = "glibc"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "8b2ff00761a77a3b273390fd7b1c865d6241fe674a666306eb1e34f1f4db4a83"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-gnu-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1d97605bb35cd0993d39de0e488b9273a231eed"
libc = "glibc"
llvm_version = "21"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "8b2ff00761a77a3b273390fd7b1c865d6241fe674a666306eb1e34f1f4db4a83"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a7aa6546feab4419151c4a44244c94ba0806033"
libc = "musl"
llvm_version = "21"
os = "linux"

    [[MLIR.download]]
    sha256 = "28b0a11fd2df97f187a748ab31cceef6ac9c4d758fbf93d1596d73fc1508d494"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-musl-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "74f1e4bab50d1d4f1ac83ccb718ec9a7621a656e"
llvm_version = "21"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "6caf81043059ed9745086b3662c12c0f8492d0592cec00e0aa19024594b6da74"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-unknown-freebsd-llvm_version+21.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82c1b07927325dc4a2287f622c1e0fd89b436531"
llvm_version = "21"
os = "windows"

    [[MLIR.download]]
    sha256 = "60afefd180c38894ffd2e2df6a5543ff9aadec052afcf3ab9716b8f812d4a4f9"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-w64-mingw32-cxx11-llvm_version+21.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "25faa4a8b774a093e48fa937829d29c49ad47d2d"
llvm_version = "21.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "515c53c393046c4691e6e62ec270f211b13e5672ef31289c2c0b38a6d7e57d74"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-apple-darwin-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87285538fb22219049d28322c9c6c3fbdc3da5bc"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "a25a48d9f4c7bf6b071cc2c6b46dc05e93dc2c8258fb775b42b63ed431f20d14"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fff98bb9fb9e2acad918ff8c00aa6b1e9a4e726d"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "eae4ed37e40911d06ca460394c30501061d5ab7ac880323f298f0eb2a9c3e835"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-linux-musl-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "1b590c1e6af29ff9829f357a55c366999795b095"
llvm_version = "21.asserts"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "7bfae52dbd8fdbe3eb9303255180a4d195915da4e48343f738a0bc07bad2c38a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.aarch64-unknown-freebsd-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "213358f49bee5a07f7b76ac85a8a6cdad5896466"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "4b9fd345dfe339bcfbcee7dfbd9baaa82a384001017a22428b39b64867b00498"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8aee5c4eb686549f6c8ddf548dcbef9f564f2081"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "d9a48cc1d565df4dc12db53a6429d5f3582372fb99301d240cf9b611d5aac7b4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a551a4830f368bfd1d69038cbbc6b2ff443c3cf6"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "b38dbdb8694d7f4625bb803292962cd2846a0571b70b9e7cfeb475ba2bade186"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "210dcd25946ecaf0b4dc14a079df5d94ce1610c6"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "da941bd36e7a7783d189544512eb0eee2301b5afbe53978a3c2f905a982da182"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb67a0e08b8aa7e59be0bbb80cfb8a897e598afb"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "02572e748cddd15584a3e529643ff57944ba383e6d055177fdf338b99c1eb950"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.i686-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d020684a7e96bc3fbdcc1ebbd1ec254fd043d83"
llvm_version = "21.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "8d87424e78429901f8f77b2b7ef0ff311823fc24f1e05094970887646c4e7b30"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.i686-w64-mingw32-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94be27692a7e5c5af5a0397e29ab62e93e18bff7"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "5f86d7a4ed8f8551899dbc963aa942e5fb3bf0f96f945d6f9df5ff82cc856723"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "780fd58f73675b6b9b46ea16caa00c05ef5ddb2f"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "4f3c397afe8505b28defbc3c78f667cbe6755f80e9ca2a2f071c70e7e56fcebe"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.riscv64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "eb432253eb7e4c756bc1226f0c5e8a14509d2060"
llvm_version = "21.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "3319b2d365581ecb82faa28dd6bfde8e81c1a2663c1978d2b3dc690840267355"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-apple-darwin-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad62c0e30c1c3256a185977eea4f318f2178e984"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "5745ae31c2242a84f0ae422f9dcc1d4b32f4e8bf9a08e0f2fb5ebf70a5a35e5d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-gnu-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ad62c0e30c1c3256a185977eea4f318f2178e984"
libc = "glibc"
llvm_version = "21.asserts"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "5745ae31c2242a84f0ae422f9dcc1d4b32f4e8bf9a08e0f2fb5ebf70a5a35e5d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ff5c1810e4c5d7ee3282f2ef8a835edb5725418"
libc = "musl"
llvm_version = "21.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "fff4d95a018538b0aec82c983d935dfef4696b59be4a01635fd4206ad1093689"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-linux-musl-cxx11-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "1ceffc2e6bbd9530e78e1efcd752cd151e2293e5"
llvm_version = "21.asserts"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "1f46e4b90dde44037d8686a19b370326309c6c39e11ccd93e3daeb506c445644"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-unknown-freebsd-llvm_version+21.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "278daecb955698e4136379d5138fe4cfa51b0176"
llvm_version = "21.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "711ea977d35c68afa39907a9879c2ecded32ed44bbbfbcf2efbaccfa016c76b5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v21.1.8+2/MLIR.v21.1.8.x86_64-w64-mingw32-cxx11-llvm_version+21.asserts.tar.gz"
