[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "5e4b92bcb0ded23069987edb9985edc92766b8be"
llvm_version = "22"
os = "macos"

    [[MLIR.download]]
    sha256 = "add8593608b10708f7bb0ad92330d0a71af9ff694e2008406a02558b57aa7c90"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-apple-darwin-llvm_version+22.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4f3f3c5ae8c62fcfeb8eb3bc7d6609a09fe6c865"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "c19502907a56ae09027cfa2039bc717aab6ddb0e93d61ac384ee076260c67c23"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a11504a6694bd02fe552d9cdd58097f2970a661"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "6a7c39a4eca9d61dae1d10f36f98fef1d036ecc274b88a250e163d6cad79464d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-linux-musl-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "1a09557d8c4083910b7d7808eb828f423831f230"
llvm_version = "22"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "07a9bfabb67067eea6c8bfe8d87a969e2ff6da5aa3c0692fdce0e1b0146dc369"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-unknown-freebsd-llvm_version+22.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b15535c94b892001c64990ebf5957ced50a809b"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "084083eb4264865743034c55391f4e57002f02cc3dcc07fe5d0b3cf7c53faa57"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5d20aeb91422be8558678dc4eb47f346152711"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "a6c7441496faab0a97cfd637f5b23013f3b94a8e2325ea6eaf67031bd95b7139"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec0c7c3a854fdc5ac618a1d890fbafe07c4c6d98"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "756d366aa792b39b16934ece05c9a199551a06b98d7d476dc4a278fddc56388d"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1511c74757b8b62a54764d70650aab75b8adfbfb"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "89859f5c65ffeb774a8399802812f1fc9eff1fa815832c91488eb2cdf830e945"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a11325a92df39ec34015bcc4531a2cdbdb24df6e"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "e6c26188d935321c3f74ef256ee6c20a0a17a8bc3cf258340c246652fa034463"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.i686-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ff246ef5fdb30d846dc9ee9f74f5910e4de1aa5"
llvm_version = "22"
os = "windows"

    [[MLIR.download]]
    sha256 = "0c5e05bbe3806277f9f0f607a07103a3d8dba265187f8dde4eb3e372cb5c46fe"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.i686-w64-mingw32-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80ae2f73a1f8cd60816f15bff07fd3c63a761342"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "a3cd771d7e660093ac4f83c2bf7ae29ddc541318ded67db7e9a830108546b2bb"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e0036215ab725f63d19181c7240999f883343dc"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "297f3a136f02d4fddd7a5251810a612e45b1a361baf432c1d2c559f2ebfb61ef"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.riscv64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "3412be0d680659a6661feeaa3ad741f4b8a93094"
llvm_version = "22"
os = "macos"

    [[MLIR.download]]
    sha256 = "55bc36695e9b02ef2856e54e0245d31dccc0d00c22094173f597308d76cbd0f5"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-apple-darwin-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b7667d1eb4789cbbca9a2825917462a1436c0d"
libc = "glibc"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "65ee7723bb5e3cd2d4aa360f46e5f31ee2cc007b4e95ea0aa9a92014ab1d3e5a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-gnu-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9b7667d1eb4789cbbca9a2825917462a1436c0d"
libc = "glibc"
llvm_version = "22"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "65ee7723bb5e3cd2d4aa360f46e5f31ee2cc007b4e95ea0aa9a92014ab1d3e5a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a35c7b5b5b73fad5dc6ab6015aa09ea1cc0f095"
libc = "musl"
llvm_version = "22"
os = "linux"

    [[MLIR.download]]
    sha256 = "3f45539fafc94184f8c3c8132ab2a87c7a5bd99639928bd9b65b341ebd259c3a"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-musl-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "b821264bb6e5290fd115abedf4fd5f92734deb74"
llvm_version = "22"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "d4479efed8d116afff02302bfb5a054bf2a49e742dc0a702cbba4a9344a98491"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-unknown-freebsd-llvm_version+22.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ce1d561e2bc9880d89c1cfb22735b9738f3c9ab"
llvm_version = "22"
os = "windows"

    [[MLIR.download]]
    sha256 = "b66d36e3b1699b2bfc8424ccb01ef18a7d8b6bed39e2b2fb68af43b88ee2ff83"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-w64-mingw32-cxx11-llvm_version+22.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "86d6b32056801d3bb15ddd716b2031bc0f144fe8"
llvm_version = "22.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "e37afa68005afe2900f6c05e4db7638ffab5915e60d006746abf864270d109db"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-apple-darwin-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce8395497c4a4bc42f7baac41c41fd6edb0a95ec"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "0e830ce21c347a726d786c2acf7f1d5fe14c2978efd6b0c4e578db5694a387ef"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a9cd1609a967f03fc62811136f1eb3f62403498"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "a611dc269e65e53ee2a30f0c5c3c209805eba629cf03a72ca7a7e555c7522284"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-linux-musl-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "aarch64"
git-tree-sha1 = "0884c2efdcf9e421fba4445048c465e52139f860"
llvm_version = "22.asserts"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "f0cd1697308ea4a6f85af701ddeaf0537625ebfa81e324d65b7b1a2d6c7a18a8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.aarch64-unknown-freebsd-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea91cc900f598f29819591226d1792d1cb6e9120"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "9b95ae8dce27d90a2f10365deac7f3c1372af8aef033589511614c61e9b8aaf3"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv6l-linux-gnueabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "286cee5c17f4bff7c5a1e011bb0b9d8a51cb6eb2"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "ec9425d0e712958684d1b2b48b5a13ccac22784a1bf393ab26529509be37e75c"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv6l-linux-musleabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b94e221fbad24ba9692da245b7b80a775faf2b13"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "fef8578f3dc3d9207d6fd302e3aa8a6a53a0a2628e546152b122ff0f578695b6"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv7l-linux-gnueabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a92154ffa7177c5ddb24558df48e4496ca842fd5"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "5295633684470d503d5ae5a2dc7d5c9e7c880ba2ebc4dce9ee961b1d0e30ce99"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.armv7l-linux-musleabihf-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11d825dce8179637799ff08aabaf27daf4a7be81"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "e0dc4fa814b74e83fe13944ad7766d809873a371883b580a7677328431012890"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.i686-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67b6381c112334fe519e490ecf24a358e5c71a71"
llvm_version = "22.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "59bdb64c4fe869da4c12fc9b26ec19af343faec38ccc0b9b996bd1c9146ce7a0"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.i686-w64-mingw32-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efc3851677cc84b479cccaadefdf12499f8d553c"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "67f0bc18b8bda9a53536eb8cdf85e2fce075c7da0547c085697d2ad84b13dee4"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.powerpc64le-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4326c8d5f3b99b33203d80414cc893e6ad36247"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "d530cb7b784ab2445c1fbd874a572dac3059a5bc28e450730c7e6d092822d3b2"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.riscv64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "7168fab6d8bda1776ab2fd563c12bef1392ddeb8"
llvm_version = "22.asserts"
os = "macos"

    [[MLIR.download]]
    sha256 = "ae245450f0854f5ae75a44a04ce85f4fb27a32713f683f6bf41c41a14889aeae"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-apple-darwin-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a59d41cab3622bee065b0a9f4afe020be499abc"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "784a91c21c5c967bf199d22e2d8def304c0b976159173b87d073e5b61f561c92"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-gnu-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a59d41cab3622bee065b0a9f4afe020be499abc"
libc = "glibc"
llvm_version = "22.asserts"
os = "linux"
sanitize = "memory"

    [[MLIR.download]]
    sha256 = "784a91c21c5c967bf199d22e2d8def304c0b976159173b87d073e5b61f561c92"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-gnu-cxx11-sanitize+memory-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce0231d8b1d46fb89b99d38824da098eca39695e"
libc = "musl"
llvm_version = "22.asserts"
os = "linux"

    [[MLIR.download]]
    sha256 = "50956e3a1830560da0d796453006795b8508aaef153c055e788576f848a67664"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-linux-musl-cxx11-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
git-tree-sha1 = "eb415d10ab1bec8d62a5422d531b6a76155d781e"
llvm_version = "22.asserts"
os = "freebsd"

    [[MLIR.download]]
    sha256 = "4e739241c65716c29e735a56c686a040cdd4dbd72a6d9641e14cf354898f3f73"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-unknown-freebsd-llvm_version+22.asserts.tar.gz"
[[MLIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75ad61e9fa7ab4675488e5de2e5a53438bad8ffb"
llvm_version = "22.asserts"
os = "windows"

    [[MLIR.download]]
    sha256 = "8a9df728bee26a39a35cf59ee96a01269f7504a859b9211e79eb5249edf8a8f8"
    url = "https://github.com/JuliaBinaryWrappers/MLIR_jll.jl/releases/download/MLIR-v22.1.8+0/MLIR.v22.1.8.x86_64-w64-mingw32-cxx11-llvm_version+22.asserts.tar.gz"
