# Autogenerated wrapper script for MLIR_jll for aarch64-apple-darwin-llvm_version+17.asserts
export libMLIR, mlir_c

using Zlib_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("MLIR")
JLLWrappers.@declare_library_product(libMLIR, "@rpath/libMLIR.dylib")
JLLWrappers.@declare_library_product(mlir_c, "@rpath/libMLIR-C.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libLLVM_jll)
    JLLWrappers.@init_library_product(
        libMLIR,
        "lib/libMLIR.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        mlir_c,
        "lib/libMLIR-C.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
