# Autogenerated wrapper script for MLIR_jll for aarch64-apple-darwin
export libMLIR

using libLLVM_jll
JLLWrappers.@generate_wrapper_header("MLIR")
JLLWrappers.@declare_library_product(libMLIR, "@rpath/libMLIR.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libLLVM_jll)
    JLLWrappers.@init_library_product(
        libMLIR,
        "lib/libMLIR.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
