# Autogenerated wrapper script for MLIR_jll for x86_64-w64-mingw32-cxx11
export libMLIR, libMLIRPublicAPI

using Zlib_jll
using libLLVM_jll
JLLWrappers.@generate_wrapper_header("MLIR")
JLLWrappers.@declare_library_product(libMLIR, "libMLIR.dll")
JLLWrappers.@declare_library_product(libMLIRPublicAPI, "libMLIRPublicAPI.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, libLLVM_jll)
    JLLWrappers.@init_library_product(
        libMLIR,
        "bin\\libMLIR.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libMLIRPublicAPI,
        "bin\\libMLIRPublicAPI.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
